{% set name = "ddsp" %}
{% set version = "1.6.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6a72710cf018955ac41662f04d0c6e3e2be8c20cc6121b1263e5ee9efe3c9b0

build:
  number: 0
  noarch: python
  entry_points:
    - ddsp_export = ddsp.training.ddsp_export:console_entry_point
    - ddsp_run = ddsp.training.ddsp_run:console_entry_point
    - ddsp_prepare_tfrecord = ddsp.training.data_preparation.ddsp_prepare_tfrecord:console_entry_point
    - ddsp_generate_synthetic_dataset = ddsp.training.data_preparation.ddsp_generate_synthetic_dataset:console_entry_point
    - ddsp_ai_platform = ddsp.training.docker.ddsp_ai_platform:console_entry_point
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - absl-py
    - crepe >=0.0.11
    - future
    - gin-config >=0.3.0
    - google-cloud-storage
    - librosa
    - mir_eval
    - numba <0.50
    - numpy
    - pydub
    - python >=3.6
    - scipy
    - six
    - tensorflow
    - tensorflow-datasets
    - tensorflow-probability

test:
  imports:
    - ddsp
    - ddsp.colab
  commands:
    - pip check
    - ddsp_export --help
    - ddsp_run --help
    - ddsp_prepare_tfrecord --help
    - ddsp_generate_synthetic_dataset --help
    - ddsp_ai_platform --help
  requires:
    - pip

about:
  home: http://github.com/magenta/ddsp
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiable Digital Signal Processing
  doc_url: https://pypi.org/project/ddsp/
  dev_url: https://github.com/magenta/ddsp

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
    - mxr-conda
